; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = Magic-wand using puara framework

[common]
platform = espressif32@6.7.0
board = adafruit_feather_esp32s3_tft
framework = arduino
board_build.partitions = min_spiffs_no_OTA.csv
lib_deps = 
    Adafruit NeoPixel
    Adafruit GFX Library
    adafruit/Adafruit ST7735 and ST7789 Library
    Adafruit BNO055
    adafruit/Adafruit BMP280 Library@^2.6.8
    https://github.com/Puara/puara-module.git
    https://github.com/Puara/puara-gestures.git#feat/projection
    https://github.com/cnmat/OSC#3.5.8
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_echo = yes
monitor_filters = default esp32_exception_decoder

; Common build flags
[flags]
build_flags =
    -std=gnu++2a
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
build_unflags =
    -std=c++11 -std=c++14 -std=c++17 -std=gnu++11 -std=gnu++14 -std=gnu++17

; Template environment, extend this for specific boards
[env:magicwand]
extends = common
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    ${flags.build_flags}
build_unflags = ${flags.build_unflags}
